### ISSUE TITLE
Fix radius logic

### ISSUE THREAD

**Issue by StGerGer** [StGerGer/vekta-processing#13]
Generated radii of planets don't take into consideration the order of magnitude of the mass. Restructure radius logic to enable this without causing very large planets.

**Comment by rvanasa** [comment]
Updated in #21 by using a square root proportionality to mass.

**Comment by StGerGer** [comment]
The mass variable isn't named properly, I'll fix it myself. But in that context, `mass` is used to reference the number that is then multiplied by `10^<power>` to give the planet's actual mass. So it's not quite fixed yet, but it's almost there 👍

**Comment by rvanasa** [comment]
Fixed #28; you can change the global scale with vekta::DISTANCE_SCALE
