### ISSUE TITLE
Refactor SpaceObject as an abstract class

### ISSUE THREAD

**Issue by StGerGer** [StGerGer/vekta-processing#24]
When vekta was first written, Processing didn't support abstract classes (or at least I was able to find documentation that suggested this). Now that it is supported, SpaceObject should be rewritten as an abstract class instead of an interface.

**Comment by rvanasa** [comment]
Implemented in #26, although there's still quite a bit of logic that can be consolidated into the abstract class rather than subclasses (e.g. position/velocity fields).

**Comment by StGerGer** [comment]
I'll leave this open until we take full advantage of the abstract class.

**Comment by rvanasa** [comment]
Did this properly in #27
