### ISSUE TITLE
Move to using Processing as a library

### ISSUE THREAD

**Issue by StGerGer** [StGerGer/vekta-processing#29]
This will enable us to take full advantage of Java 7/8 functionality. We can also use Maven, as well as writing JUnit tests for everything.

**Comment by StGerGer** [comment]
In a similar vein, what if we started using [PixelFlow](https://diwi.github.io/PixelFlow/) for particle effects and post processing? It might be a little overkill, but it's worth looking into.

**Comment by StGerGer** [comment]
[This article](https://processing.org/tutorials/eclipse/) describes how to use Processing as a library.

**Comment by rvanasa** [comment]
Fully completed in #36
