### ISSUE TITLE
Add Log Pane

### ISSUE THREAD

**Issue by StGerGer** [StGerGer/vekta-processing#49]
Create a Log pane built on five `List<SpaceObject>`s (in decreasing order of information stored):
 - Properties the player owns
 - Planets the player has scanned while docked on the planet
 - Planets the player has landed on
 - Objects the player has targeted
 - Objects within a certain range of the player

For each object in the list, get information on that planet. We assume that the planet can broadcast its information through the network of the universe, so the information can be current.

There should also be a way to search the lists, because they'll probably get very long.

When an entry is selected, the information should be displayed on the right side of the screen. I'll figure out what exactly is displayed for each category in a bit.

I might end up conglomerating the lists into one and have a second list that has the category of the entry.

**Comment by rvanasa** [comment]
Closing since we now have a pretty good log pane implementation.
