### ISSUE TITLE
Split planets when hit with projectile

### ISSUE THREAD

**Issue by StGerGer** [StGerGer/vekta-processing#8]
When a planet is hit by a projectile, right now it is removed. I'd like for it to be removed and two planets spawned in its place, whose net mass are equivalent to the initial planet. I'd also like to see an initial force applied to each in opposite directions, so that the planets do not just collide after one frame. Similarly, they must be offset by at least the sum of their radii so that they will not instantaneously collide.

**Comment by StGerGer** [comment]
This will most likely be handled in the `onDestroy()` function for `Planet`.

**Comment by StGerGer** [comment]
This doesn't seem to be working. I'll double check the commit and see.

**Comment by rvanasa** [comment]
Implemented in #22
